# Generated by Django 4.2.3 on 2023-10-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('coustomer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coustomer_email', models.CharField(max_length=100, null=True)),
                ('coustomer_password', models.CharField(max_length=100, null=True)),
                ('coustomer_usertype', models.CharField(max_length=255, null=True)),
                ('coustomer_status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_description', models.CharField(max_length=100, null=True)),
                ('product_rate', models.CharField(max_length=200)),
                ('product_stock', models.IntegerField(null=True)),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopswift.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_size', models.CharField(max_length=100, null=True)),
                ('cart_quantity', models.IntegerField(null=True)),
                ('cart_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopswift.product')),
            ],
        ),
    ]
