# Generated by Django 4.2.3 on 2023-10-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopswift.customer'),
        ),
    ]
