# Generated by Django 4.2.3 on 2023-10-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0002_cart_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product_amount',
            field=models.IntegerField(null=True),
        ),
    ]
