# Generated by Django 4.2.3 on 2023-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0003_cart_cart_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
