# Generated by Django 4.2.3 on 2023-10-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0004_customer_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='coustomer_status',
            new_name='coustomer_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='coustomer_usertype',
            new_name='coustomer_place',
        ),
    ]
