# Generated by Django 4.2.3 on 2023-11-04 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0005_rename_coustomer_status_customer_coustomer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_rate', models.IntegerField()),
                ('order_product_quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopswift.customer')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopswift.product')),
            ],
        ),
    ]
