# Generated by Django 4.2.3 on 2023-11-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopswift', '0007_orders_order_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_product_rate',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
